// GENERATED by pa-spawn-planet/server/build.js. Do not edit by hand.
// Stock source: media/server-script/states/landing.js (md5 d89b32415e066ce68b84e4fad6c88dd0)
// Search for "Spawn Planet Picker" to find the patched regions.
var console = require('console'); // temporary workaround
var main = require('main');
var server = require('server');
var sim = require('sim');
var utils = require('utils');
var _ = require('thirdparty/lodash');
var vec = require('vec');
var chat_utils = require('chat_utils');

var client_state = {
    armies: [],
    zone_radius: 0,
    ranked: false
};
var playing = false;

var players = {};

var armies = [];
var diplomaticStates = {};

var game_options = {};

var forceLandingTimeout;

var cleanup = [];
var cleanupOnEntry = [];

var FORCE_START_TIMEOUT = 2 * 60 * 1000; /* in ms */

// ---- Spawn Planet Picker (com.pa.bteam.spawnplanet-server) -----------------
// Lets the lobby designate a starting planet per army. Picks arrive two ways:
//   * AI armies: the stock lobby stores whatever landing policy string the host
//     set, so "planet:N" reaches us as slot.landing_policy.
//   * Any army: the host client sends spawn_planet_assignments once the landing
//     phase begins, mapping player/AI client ids to policy strings.
var SPAWN_PLANET_PREFIX = 'planet:';
var spawnPlanetAssignments = {};   // client id -> policy string
var spawnPlanetSlotIds = [];       // armies index -> [client id per slot, in slot order]
var spawnPlanetNames = [];         // planet index -> display name
var allPlanetZones = null;         // pristine copy of the generated zones
var spawnPlanetFallbackZones = {}; // planet index -> zones generated for starting planets the map rules left empty

console.log('[spawnplanet] landing.js override active');

function spawnPlanetLog() {
    console.log.apply(console, ['[spawnplanet]'].concat(Array.prototype.slice.call(arguments)));
}

function spawnPlanetIndex(policy) {
    if (!_.isString(policy) || policy.indexOf(SPAWN_PLANET_PREFIX) !== 0)
        return -1;
    var index = Number(policy.substr(SPAWN_PLANET_PREFIX.length));
    if (!_.isFinite(index))
        return -1;
    var hasZones = _.any(allPlanetZones, function (element) {
        return element && element.planet_index === index && element.positions.length;
    });
    if (!hasZones && spawnPlanetFallbackZones[index] && spawnPlanetFallbackZones[index].positions.length)
        hasZones = true;
    return hasZones ? index : -1;
}

// armies index -> planet index. The first pick in slot order wins for an army,
// which matches the lobby showing one dropdown for a shared-army team.
function spawnPlanetChoices() {
    var result = {};
    _.forEach(armies, function (army, armyIndex) {
        var ids = spawnPlanetSlotIds[armyIndex] || [];
        var chosen = -1;
        _.forEach(ids, function (id) {
            if (chosen >= 0 || !id)
                return;
            var policy = spawnPlanetAssignments[id];
            if (policy === undefined) {
                var ai = _.find(army.ai, function (slot) { return slot.client && slot.client.id === id; });
                if (ai)
                    policy = ai.landing_policy;
            }
            var index = spawnPlanetIndex(policy);
            if (index >= 0)
                chosen = index;
        });
        if (chosen >= 0)
            result[armyIndex] = chosen;
    });
    return result;
}

function spawnPlanetMakeZone(position, element) {
    return { position: position, planet_index: element.planet_index, radius: element.radius };
}

// Sent to each client inside server_state so the UI can show that the
// override is live and which planet the army was designated.
function spawnPlanetClientInfo(army) {
    var choices = spawnPlanetChoices();
    var index = (army && _.has(choices, army.index)) ? choices[army.index] : -1;
    return {
        active: true,
        planet_index: index,
        planet_name: index >= 0 ? (spawnPlanetNames[index] || ('Planet ' + (index + 1))) : null,
        zone_planets: army ? _.uniq(_.pluck(army.zones, 'planet_index')) : []
    };
}
// ---------------------------------------------------------------------------
var START_PLAYING_DELAY = 5; /* in seconds */

var debugging = false;

_.assign(module, require('states/playing_shared').import(module));

function debug_log(object) {
    if (debugging)
        console.log(JSON.stringify(object, null, '\t'));
}

function startPlaying() {
    var count = START_PLAYING_DELAY;

    playing = true;

    (function countdownToPlaying() {
        server.broadcastCountdownEvent(count);
        count -= 1;

        if (count > 0)
            _.delay(countdownToPlaying, 1000);
        else {
            main.setState(main.states.playing, {
                players: players,
                armies: armies,
                diplomaticStates: diplomaticStates,
                armyDesc: client_state.armies,
                game_options: game_options,
                ranked: client_state.ranked
            });
        }
    })();
}

var updateArmyStateShared = updateArmyState;
var updateArmyState = function(transmit) {
    updateArmyStateShared(transmit);

    var launchCount = _.reduce(armies, function(sum, army) { return sum + !!army.desc.landing; }, 0);
    if (!launchCount && !playing)
        selectAISpawnsAndStartGame();
};

// Spawn Planet Picker: does not consume `zones`, so it can run again when the
// host sends assignments. Stock behaviour is preserved when nobody picked.
function assignZones(zones) {
    if (!armies.length)
        return;

    var elements = _.filter(zones, function (element) { return element && element.positions; });
    var pools = _.map(elements, function (element) {
        return { planet_index: element.planet_index, radius: element.radius, positions: element.positions.slice() };
    });
    var choices = spawnPlanetChoices();

    _.forEach(armies, function (army) {
        army.zones = [];
    });

    // 1. Armies that picked a planet take that planet's zones first.
    var choosersByPlanet = {};
    _.forEach(choices, function (planetIndex, armyIndex) {
        (choosersByPlanet[planetIndex] = choosersByPlanet[planetIndex] || []).push(Number(armyIndex));
    });
    _.forEach(choosersByPlanet, function (choosers, planetIndex) {
        var pool = _.find(pools, { planet_index: Number(planetIndex) });
        if (!pool || !pool.positions.length) {
            // The map rules gave this planet no zones for this army count; use
            // the fallback set. It is deliberately not added to `pools`, so
            // armies that did not pick this planet never land there.
            var fallback = spawnPlanetFallbackZones[planetIndex];
            if (!fallback || !fallback.positions.length)
                return;
            pool = { planet_index: Number(planetIndex), radius: fallback.radius, positions: fallback.positions.slice() };
        }
        var list = pool.positions;
        if (list.length >= choosers.length) {
            var next = 0;
            while (list.length) {
                armies[choosers[next % choosers.length]].zones.push(spawnPlanetMakeZone(list.pop(), pool));
                next = next + 1;
            }
        }
        else {
            // Fewer zones than armies that want this planet: they share them.
            _.forEach(choosers, function (armyIndex) {
                _.forEach(list, function (position) {
                    armies[armyIndex].zones.push(spawnPlanetMakeZone(position, pool));
                });
            });
            list.length = 0;
        }
    });

    // 2. Everyone else gets the remaining zones round-robin, as stock does.
    var others = _.filter(_.range(armies.length), function (armyIndex) { return !_.has(choices, armyIndex); });
    if (others.length) {
        var army_index = 0;
        _.forEach(pools, function (pool) {
            var list = pool.positions;
            while (list.length) {
                armies[others[army_index % others.length]].zones.push(spawnPlanetMakeZone(list.pop(), pool));
                army_index = army_index + 1;
            }
        });
    }

    // 3. Never leave an army without somewhere to land.
    _.forEach(armies, function (army) {
        if (army.zones.length)
            return;
        _.forEach(elements, function (element) {
            _.forEach(element.positions, function (position) {
                army.zones.push(spawnPlanetMakeZone(position, element));
            });
        });
    });

    if (!_.isEmpty(choices))
        spawnPlanetLog('zones assigned with picks ' + JSON.stringify(choices) + ' planets per army ' +
            JSON.stringify(_.map(armies, function (army) { return _.uniq(_.pluck(army.zones, 'planet_index')); })));
}

function selectAISpawnsAndStartGame()
{
    var planetsWithPlayers = {};
    _.forEach(players, function (player)
    {
        planetsWithPlayers[player.spawn.planet_index] = true;
    });

    var withPlayer = function (zone)
    {
        if (planetsWithPlayers[zone.planet_index])
            return true;
    };

    var noPlayers = _.size(players) == 0;

    var aiPlanets = {};

    var withAI = function (zone)
    {
        if (aiPlanets[zone.planet_index])
            return true;
    };

    _.forEach(armies, function (army)
    {
        _.forEach(army.ai, function (ai)
        {
            var zones = [];

            switch (ai.landing_policy)
            {
                default: // fallthrough

                case 'no_restriction':

                    zones = _.reject(army.zones, withAI); // avoid other AI

                    break;

                case 'on_player_planet':

                    zones = _.filter(army.zones, withPlayer); // spawn with players

                    if (_.isEmpty(zones))
                        zones = _.reject(army.zones, withAI); // if no zones on player planet then just avoid other AI

                    break;

                case 'off_player_planet':

                    if (noPlayers)
                        zones = _.reject(army.zones, withAI); // avoid other AI
                    else
                    {
                        zones = _.reject(army.zones, withPlayer); // avoid players
                        zones = _.reject(zones, withAI); // avoid other AI

                        if (_.isEmpty(zones))
                            zones = _.reject(army.zones, withPlayer); // if no zones then just avoid players
                    }

                    break;
            }

// if no zones igore policy

            if (_.isEmpty(zones))
                zones = army.zones;

            ai.spawn = army.sim.aiSpawnLocation(zones);

            aiPlanets[ai.spawn.planet_index] = true;
        });
    });

    startPlaying();
}

function validateSpawnPoint(zones, location, planet_index) {

    return _.any(zones, function (zone) {
        var zoneRadiusSqr = zone.radius * zone.radius;
        var inRadius = game_options.land_anywhere || vec.distSqr3(location, zone.position) <= zoneRadiusSqr;
        return inRadius && planet_index === zone.planet_index;
    });
}

function forcePlayerLanding(player) {
    if (!player)
        return;

    var zone = _.sample(player.army.zones)
    if (!zone)
        return;

    playerMsg_landingLocationSelected({
        client: player.client,
        payload: {
            location: zone.position,
            planet_index: zone.planet_index
        }
    });
}

function playerMsg_landingLocationSelected(msg) {

    var response = server.respond(msg);
    var player = players[msg.client.id];
    if (!msg.payload)
        return response.fail("Invalid message");
    if (player.spawn)
        return response.fail("Player has already selected a landing zone");
    var location = vec.parse3(msg.payload.location);
    if (!location || !validateSpawnPoint(player.army.zones, location, msg.payload.planet_index))
        return response.fail("Invalid spawn point");
    player.spawn = msg.payload;
    var armyDesc = player.army.desc;
    --armyDesc.landing;
    if (!armyDesc.landing)
        delete armyDesc.landing;
    // Note: Due to some legacy code in the client interface,
    // this must be sent as an explicit message
    msg.client.message({
        message_type:'client_state',
        payload: exports.getClientState(msg.client)
    });
    response.succeed();
    updateArmyState(true);
}

// Spawn Planet Picker: mirror main.setState's per-client server_state send so
// every client redraws its green zones after a reassignment.
function spawnPlanetBroadcastState() {
    var message = { message_type: 'server_state', payload: exports.hello_response };
    if (!message.payload.data)
        message.payload.data = {};
    _.forEach(server.clients, function (client) {
        if (!client.connected)
            return;
        message.payload.data.client = exports.getClientState(client);
        client.message(message);
    });
    delete message.payload.data.client;
}

function spawnPlanetReassign() {
    if (!allPlanetZones)
        return false;
    // Armies that already landed keep the zones they were validated against.
    var landed = {};
    _.forEach(players, function (player) {
        if (player.spawn && player.army)
            landed[player.army.index] = player.army.zones;
    });
    assignZones(allPlanetZones);
    _.forEach(landed, function (zones, armyIndex) {
        if (armies[armyIndex])
            armies[armyIndex].zones = zones;
    });
    spawnPlanetBroadcastState();
    return true;
}

function playerMsg_spawnPlanetAssignments(msg) {
    var response = server.respond(msg);
    var player = players[msg.client.id];
    if (!player || !player.creator)
        return response.fail("Only the host can assign spawn planets");
    if (!msg.payload || !_.isObject(msg.payload.assignments))
        return response.fail("Invalid payload");

    spawnPlanetAssignments = _.clone(msg.payload.assignments);
    spawnPlanetLog('assignments received ' + JSON.stringify(spawnPlanetAssignments));

    if (!spawnPlanetReassign())
        return response.fail("Landing zones not ready");

    response.succeed({
        planets_per_army: _.map(armies, function (army) { return _.uniq(_.pluck(army.zones, 'planet_index')); })
    });
}

function playerMsg_surrender(msg) {
    var response = server.respond(msg);

    var player = players[msg.client.id];
    if (!player)
        return response.fail("Player not found");

    if (player.has_surrendered)
        return response.fail("Player already surrendered");

    if (!player.spawn)
        forcePlayerLanding(player);

    player.has_surrendered = true;
    response.succeed();
}


function forceLanding() {
    forceLandingTimeout = undefined;
    // Pick a random landing for each player if time runs out.
    _.forEach(players, function(player) {
        if (player.spawn)
            return;

        forcePlayerLanding(player);
    });

    if (!playing)
    {
        console.error("forceLanding() did not result in a transition to playing state.  Armies:", JSON.stringify(armies));
        _.forEach(armies, function(army) {
            if (army.desc)
                delete army.desc.landing;
        });
        selectAISpawnsAndStartGame();
    }
}

function setupPlanets(system) {
    _.forEach(system.planets, function (planet, index) {
        _.forEach(planet.units, function (unit) {
            var armyIndex = _.has(unit, 'army') ? unit.army : 0;
            var army = armyIndex == -1 ? undefined : armies[armyIndex];
            spawnUnit({
                army: army,
                spec: unit.unit_spec,
                planet: sim.planets[index],
                position: unit.pos,
                orientation: unit.orient
            });
        });
    });
}

exports.url = 'coui://ui/main/game/live_game/live_game.html';
exports.enter = function(config) {
    if (main.spectators) {
        if (server.beacon)
            server.beacon.state = 'landing';
    } else {
        server.beacon = undefined;
        server.close("Game in progress");
    }

    var clean_config = _.cloneDeep(config);

    _.forEach(clean_config.armies, function(army)
    {
        _.forEach(army.slots, function(slot)
        {
            var client = slot.client;

            if (client)
            {
                client.debugDesc = '';

                var data = client.data;

                if (data)
                {
                    try
                    {
                        data = JSON.parse(data);
                        if (data.password)
                        {
                            data.password = '';
                            client.data = JSON.stringify(data);
                        }
                    }
                    catch (e)
                    {

                    }
                }
            }
        })
    });

    _.forEach(clean_config.players, function(player)
    {
        var client = player.client;

        if (client)
        {
            client.debugDesc = '';

            var data = client.data;

            if (data)
            {
                try
                {
                    data = JSON.parse(data);

                    if (data.password)
                    {
                        data.password = '';
                        client.data = JSON.stringify(data);
                    }
                }
                catch (e)
                {

                }
            }
        }
    })

    // store the config in case we want use save/load
    server.setGameConfig(JSON.stringify(clean_config));

    client_state.sim_speed_multiplier = sim.speed;
    client_state.ranked = config.ranked;
    client_state.force_start = config.game.system.force_start;
    game_options = config.game.game_options;


    // Note: It's quite possible this does not have correct semantics.  This is
    // kind of a "hope" for correctness on a server that runs the landing
    // state more than once.
    _.forEachRight(cleanupOnEntry, function(c) { c(); });
    cleanupOnEntry = [];

    initArmyState(config);

    spawnPlanetSlotIds = _.map(config.armies, function (army) {
        return _.map(army ? army.slots : [], function (slot) {
            return slot && slot.client ? slot.client.id : null;
        });
    });
    spawnPlanetAssignments = {};
    spawnPlanetNames = _.pluck((config.game && config.game.system && config.game.system.planets) || [], 'name');

    _.forEach(sim.players, function(player) {
        var client = player.client;
        utils.pushCallback(client, 'onDisconnect', function(onDisconnect) {
            updateConnectionState();
            if (!player.spawn)
                forcePlayerLanding(player);

            return onDisconnect;
        });
        cleanup.push(function () { client.onDisconnect.pop(); });

    });
    utils.pushCallback(server, 'onConnect', updateConnectionState);
    cleanup.push(function() { server.onConnect.pop(); });

    console.log("Created", sim.armies.length, "armies and", sim.players.length, "players");

    var planet_zones = {};
    var total_zones = 0;
    var force_random = false;

    var processPlanet = function (planet, index) {
        var planetConfig = config.game.system.planets[index];
        var planetRadius = planetConfig.generator.radius;

        var maxZonesPerArmy;
        if (planetConfig.generator.landingZonesPerArmy > 0)
            maxZonesPerArmy = planetConfig.generator.landingZonesPerArmy;
        else
            maxZonesPerArmy = Math.min(Math.ceil(planetRadius / 300), 4);

        var zoneRadius;
        if (planetConfig.generator.landingZoneSize > 0)
            zoneRadius = planetConfig.generator.landingZoneSize;
        else
            zoneRadius = planetRadius / 5;

        var bufferRadius = planetRadius * 0.2;

        if (planetConfig.starting_planet) {
            planet_zones[index] = planet.genMetalAndLandingSpots(maxZonesPerArmy,
                                                                 zoneRadius,
                                                                 bufferRadius,
                                                                 sim.armies.length,
                                                                 force_random);
            total_zones = total_zones + planet_zones[index].positions.length;
        }
        else
            planet.genMetalSpots();

        if (planet_zones[index])
            planet_zones[index].planet_index = index;
    }

    _.forEach(sim.planets, processPlanet);

    // check that we have enough zones for each army, and regerate if required
    if (total_zones < sim.armies.length)
    {
        planet_zones = {};
        force_random = true;
        _.forEach(sim.planets, processPlanet);
    }

    if (_.isEmpty(planet_zones)) {
        // TODO: This should probably do something a little more graceful.  Or just
        // never fail.
        console.error("Unable to create landing zones.  Aborting.");
        server.exit();
        return;
    }

    if (game_options.shuffle_landing_zones)
        planet_zones = _.shuffle(planet_zones);

    allPlanetZones = _.cloneDeep(_.filter(planet_zones, Boolean));

    // Spawn Planet Picker: a starting planet whose custom landing-zone rules
    // exclude this army count ends up with no zones, so nobody could pick it.
    // Generate a random fallback set for each such planet, exactly as the stock
    // "not enough zones" path does, and keep it aside for armies that pick it.
    spawnPlanetFallbackZones = {};
    _.forEach(sim.planets, function (planet, index) {
        var planetConfig = config.game.system.planets[index];
        if (!planetConfig || !planetConfig.starting_planet || !planetConfig.generator)
            return;
        var existing = _.find(allPlanetZones, { planet_index: index });
        if (existing && existing.positions.length)
            return;
        var planetRadius = planetConfig.generator.radius;
        var fallbackZonesPerArmy = planetConfig.generator.landingZonesPerArmy > 0
            ? planetConfig.generator.landingZonesPerArmy
            : Math.min(Math.ceil(planetRadius / 300), 4);
        var fallbackZoneRadius = planetConfig.generator.landingZoneSize > 0
            ? planetConfig.generator.landingZoneSize
            : planetRadius / 5;
        try {
            var generated = planet.genMetalAndLandingSpots(fallbackZonesPerArmy, fallbackZoneRadius, planetRadius * 0.2, sim.armies.length, true);
            if (generated && generated.positions && generated.positions.length) {
                generated.planet_index = index;
                spawnPlanetFallbackZones[index] = generated;
                spawnPlanetLog('generated ' + generated.positions.length + ' fallback zones on planet ' + index + ' (' + (spawnPlanetNames[index] || '?') + ')');
            }
        }
        catch (e) {
            spawnPlanetLog('fallback zone generation failed for planet ' + index + ': ' + e);
        }
    });

    assignZones(allPlanetZones);

    if (env.indexOf('--debug-landing-zones') < 0) {
        var forceTime = FORCE_START_TIMEOUT;
        if (config.game.system.force_start) {
            forceTime = 100;
        }

        forceLandingTimeout = setTimeout(forceLanding, forceTime);
        cleanup.push(function() {
            if (forceLandingTimeout !== undefined)
                clearTimeout(forceLandingTimeout);
        });
    }

    var transientHandlers = {
        landing_location_selected: playerMsg_landingLocationSelected,
        spawn_planet_assignments: playerMsg_spawnPlanetAssignments,
        surrender: playerMsg_surrender
    };
    _.assign(transientHandlers, chat_utils.getChatHandlers(players, { listen_to_spectators: game_options.listen_to_spectators }));

    cleanup.push(server.setHandlers(transientHandlers));
    cleanup.push(server.setHandlers(playerMsg_handlers));

    setupPlanets(config.game.system);

    // Make sure the army state is consistent (handles no-player condition)
    updateArmyState(false);

    sim.paused = false;

    return client_state;
};

exports.exit = function(newState) {
    _.forEachRight(cleanup, function(c) { c(); });
    cleanup = [];
    return true;
};

exports.getClientState = function(client) {
    var player = players[client.id];
    if (!player) { //if there is no player you are a spectator
        return {
            vision_bits: sim.armies.getVisionBits(client),
            game_options: game_options,
            spawn_planet_picker: spawnPlanetClientInfo(null)
        };
    }
    var army = player.army;
    return {
        army_id: army.desc.id,
        vision_bits: sim.armies.getVisionBits(client),
        zones: army.zones,
        landing_position: player.spawn,
        game_options: game_options,
        spawn_planet_picker: spawnPlanetClientInfo(army)
    };
};
